name: Lint code

on: [push]

jobs:
  lint:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: true

    steps:
      - name: Checkout code
        uses: actions/checkout@v2
        with:
          ref: ${{ github.head_ref }}

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.2'
          extensions: json, zip, dom, curl, libxml, mbstring
          tools: composer:v2
          coverage: none

      - name: Install PHP dependencies
        run: composer update --no-interaction --no-progress

      - name: Run Linter
        run: composer run lint

      - name: Commit changes
        uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_message: 'chore: fix styling'
