name: Run Tests

on: ["push","pull_request"]

jobs:
  tests:
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: true
      matrix:
        os: ["ubuntu-latest","macos-latest","windows-latest"]
        php: ["8.3","8.2","8.1","8.0","7.4"]

    name: PHP ${{ matrix.php }} - ${{ matrix.os }}

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Boot MySQL
        run: sudo systemctl start mysql.service

      - name: Initialize database
        run: |
          mysql -e 'CREATE DATABASE atest;' \
          -u root -p root

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: ${{ matrix.php }}
          extensions: json, zip, dom, curl, libxml, mbstring
          tools: composer:v2
          coverage: xdebug

      - name: Install PHP dependencies
        run: composer update --no-interaction --no-progress

      - name: Run Tests
        run: composer run test -- --flags=coverage
